on:
  issues:
    types:
    - labeled
jobs:
  demonstrate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: benluddy/reviewdog-action@v1
      with:
        github_token: ${{ github.token}}
        reviewable_label: foobar
        event_path: ${{ github.event_path }}
